### ISSUE TITLE
Does not work on latest binary ninja dev build

### ISSUE THREAD

**Issue by fabianfreyer** [ImNotAVirus/delphi_ninja#1]
Loading fails on Version 2.4.3107-dev (2021-11-12 05:12:55):

```
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/__init__.py", line 5, in <module>
    from .bnhelpers import BNHelpers
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/bnhelpers.py", line 7, in <module>
    class BNHelpers(object):
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/bnhelpers.py", line 34, in BNHelpers
    def _add_vmt_fields(bv: BinaryView, vmt: DelphiVMT, out_struct: types.Structure) -> bool:
AttributeError: module 'binaryninja.types' has no attribute 'Structure'
Python plugin 'delphi_ninja' could not be loaded
```

**Comment by ImNotAVirus** [comment]
Thanks for the issue !
I'll try to fix it as soon as possible.
