### ISSUE TITLE
Doesn't work with Binary Ninja 3.1.3469 Personal

### ISSUE THREAD

**Issue by strmotors** [ImNotAVirus/delphi_ninja#5]
It doesn't work with the Binary Ninja. Gives following errors when I try to analyze.

```
Traceback (most recent call last):
  File "D:\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 120, in _default_action
    action(view_obj)
  File "C:\Users\xxx\AppData\Roaming\Binary Ninja\repositories\community\plugins\ImNotAVirus_delphi_ninja\__init__.py", line 103, in analyze_delphi_vmts
    clear_tags(bv, type_name)
  File "C:\Users\xxx\AppData\Roaming\Binary Ninja\repositories\community\plugins\ImNotAVirus_delphi_ninja\__init__.py", line 52, in clear_tags
    code_section = bv.sections['CODE']
KeyError: 'CODE'
Traceback (most recent call last):
  File "D:\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 120, in _default_action
    action(view_obj)
  File "C:\Users\xxx\AppData\Roaming\Binary Ninja\repositories\community\plugins\ImNotAVirus_delphi_ninja\__init__.py", line 103, in analyze_delphi_vmts
    clear_tags(bv, type_name)
  File "C:\Users\xxx\AppData\Roaming\Binary Ninja\repositories\community\plugins\ImNotAVirus_delphi_ninja\__init__.py", line 52, in clear_tags
    code_section = bv.sections['CODE']
KeyError: 'CODE'
```

**Comment by ImNotAVirus** [comment]
Hi, sorry for the long response time.  
Currently this plugin only works for PE (Windows). Do you still have your binary for me to look at?

**Comment by ImNotAVirus** [comment]
I'm closing this ticket because the plugin is working for me. Don't hesitate to reopen it if it doesn't for you for the same reason :)
